fofb_cc_gtp7_if: fix missing default value for ILA probe0
This was causing the following erro on Vivado 2018.3:
ERROR: [Chipscope 16-213] The debug port
'cmp_fofb_ctrl_wrapper_0/cmp_wb_fofb_ctrl_wrapper/
cmp_fofb_ctrl_wrapper/cmp_fofb_cc_top/
GT_IF/CSCOPE_GEN.ila_core_inst/probe0'
has 3 unconnected channels (bits). This
will cause errors during implementation.